name: frontend_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0 # Font chữ đẹp
  font_awesome_flutter: ^10.7.0 # Icon đẹp
  carousel_slider: ^5.0.0 # Slider ảnh
  smooth_page_indicator: ^1.2.0 # Hiệu ứng chuyển trang
  go_router: ^16.0.0 # Quản lý điều hướng
  dio: ^5.7.0 # Gửi request HTTP
  provider: ^6.1.5 # Quản lý trạng thái
  url_launcher: ^6.3.0 # Mở link ngoài
  flutter_html: ^3.0.0 # Hiển thị nội dung HTML
  html: ^0.15.0 # Xử lý HTML
  intl: ^0.19.0 # Định dạng ngày tháng
  month_picker_dialog: ^6.5.0 # Lọc lịch làm việc của bs theo tháng
  firebase_core: ^3.5.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.1.0 # đăng nhập với google
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^8.0.0
  jwt_decode: ^0.3.1
  flutter_localizations:  
    sdk: flutter



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/