name: frontend_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0
  go_router: ^16.0.0
  dio: ^5.7.0
  provider: ^6.1.5
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0
  html: ^0.15.0
  intl: ^0.19.0
  month_picker_dialog: ^6.5.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.3
  flutter_localizations:  # Thêm dòng này
    sdk: flutter



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/